name: texas-env

# Add these two lines
channels:
  - conda-forge
channel_priority: strict

dependencies:
  # --- Geo Stack (Complex Dependencies) ---
  - geopandas
  - shapely
  - cartopy
  - "pyproj<3.6"
  - rtree
  - pyogrio
  - mapclassify
  - geopy

  # --- xESMF Stack (Complex Dependencies) ---
  - xesmf
  - esmpy
  - esmf
  - mpich
  - hdf5
  - libnetcdf

  # --- Stan & Other Tools ---
  - cmdstanpy>=1.0
  - stanio
  - typing-extensions
  - anywidget
  - ipylab
  - duckdb
  - pyarrow
  - sqlalchemy
  - pydantic

  # --- Pip-only packages & Local Install ---
  - pip:
    - baysplinepy
    - baysparpy
    - pygwalker
    - -e .