[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TEXAS"
version = "0.1.0"
authors = [{ name = "Ronnakrit Rattanasriampaipong", email = "rattanasriampaipong.r@gmail.com" }]
description = "Bayesian GDGT–temperature utilities"
readme = "README.md"                    # ensure this file exists
requires-python = ">=3.8"
license = { text = "MIT" }              # SPDX expression or text to avoid deprecation warning
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

# runtime deps
dependencies = [
  "numpy>=1.18",
  "xarray>=0.16",
  "cmdstanpy>=1.0",
  "typing-extensions>=3.7.4",
  "scipy>=1.7",
  "pandas",
  "baysparpy",
  "baysplinepy"
]

[project.optional-dependencies]
plotting = [
    "matplotlib<3.5",
    "proplot==0.9.7",
    "cmocean",
    "setuptools<81"
]

dev = [
  "ipykernel",
  "pytest",
  "mkdocs"
]

[tool.setuptools]
packages = ["TEXAS"]

[tool.setuptools.package-data]
TEXAS = ["stan_models/*.stan"]

[project.urls]
"Homepage" = "https://github.com/PaleoLipidRR/TEXAS"
"Bug Tracker" = "https://github.com/PaleoLipidRR/TEXAS/issues"
