# docker/Dockerfile.phylo
FROM mambaorg/micromamba:1.5.10-bookworm

# Need unzip for NCBI datasets zips (and core utils are already present)
USER root
RUN apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*
USER mambauser

RUN micromamba create -y -n phylo -c conda-forge -c bioconda \
    python=3.10 \
    gtdbtk=2.4.1 \
    ncbi-datasets-cli \
    pplacer hmmer prodigal fasttree mafft trimal iqtree \
    mash skani \
 && micromamba run -n phylo pip install --no-cache-dir "gtdbtk==2.4.1" \
 && micromamba clean -a -y

SHELL ["/bin/bash", "-lc"]
ENV MAMBA_DEFAULT_ENV=phylo
ENV PATH=/opt/conda/envs/phylo/bin:$PATH

# Defaults so GTDB-Tk finds the DB & pplacer uses a fast/safe scratch
ENV GTDBTK_DATA_PATH=/gtdb
ENV TMPDIR=/app/data/phylo/scratch

# Workspace
WORKDIR /workspace


CMD ["/bin/bash"]
