services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    container_name: texas_gui
    ports:
      - "8503:8501"    # host:container
    environment:
      TEXAS_INV_CACHE: "/app/data/cache/TEXAS_invT_posterior_cache"
      TEXAS_FWD_CACHE: "/app/data/cache/TEXAS_posterior_cache"
    volumes:
      - ../data:/app/data:ro
    restart: unless-stopped
    profiles: ["app"]

  docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile.docs
    container_name: texas_docs
    volumes:
      - ..:/docs
    ports:
      - "8000:8000"
    command: ["serve", "--dev-addr=0.0.0.0:8000"]
    profiles: ["docs"]

  full:
    image: ghcr.io/paleolipidrr/texas:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    container_name: texas_full
    command: >
      jupyter lab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --allow-root
        --ServerApp.token=''
        --ServerApp.password=''
        --ServerApp.root_dir=/home/micromamba/app
        --IdentityProvider.token=''
    ports:
      - "8888:8888"
    profiles: ["full"]

  demo:
    build:
      context: ..
      dockerfile: docker/Dockerfile.demo
    container_name: texas_demo
    command: >
      jupyter lab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --NotebookApp.token=''
        --NotebookApp.password=''
        --notebook-dir=/home/micromamba/app
    ports:
      - "8889:8888"
    profiles: ["demo"]

  si:
    build:
      context: ..
      dockerfile: docker/Dockerfile.si
    container_name: texas_si
    command: >
      jupyter lab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --NotebookApp.token=''
        --NotebookApp.password=''
        --notebook-dir=/home/micromamba/app
    ports:
      - "8890:8888"
    profiles: ["si"]
