// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace hier_crtp_univ_prior_approx_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 23> locations_array__ =
  {" (found before start of program)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 15, column 2 to column 35)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 16, column 2 to column 37)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 17, column 2 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 18, column 2 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 22, column 2 to column 47)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 23, column 2 to column 45)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 24, column 2 to column 45)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 25, column 2 to column 42)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 27, column 9 to column 15)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 27, column 2 to column 85)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 28, column 2 to column 50)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 2, column 2 to column 22)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 3, column 9 to column 15)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 3, column 2 to column 24)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 4, column 9 to column 15)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 4, column 2 to column 31)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 6, column 2 to column 21)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 7, column 2 to column 19)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 8, column 2 to column 20)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 9, column 2 to column 18)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 10, column 2 to column 20)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/hier_crtp_univ_prior_approx.stan', line 11, column 2 to column 18)"};
class hier_crtp_univ_prior_approx_model final : public model_base_crtp<hier_crtp_univ_prior_approx_model> {
 private:
  int N_crtp;
  Eigen::Matrix<double,-1,1> t_crtp_data__;
  Eigen::Matrix<double,-1,1> scaledRI_crtp_data__;
  double prior_mean_t0;
  double prior_sd_t0;
  double prior_mean_k;
  double prior_sd_k;
  double prior_mean_b;
  double prior_sd_b;
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_crtp{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> scaledRI_crtp{nullptr, 0};
 public:
  ~hier_crtp_univ_prior_approx_model() {}
  hier_crtp_univ_prior_approx_model(stan::io::var_context& context__,
                                    unsigned int random_seed__ = 0,
                                    std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "hier_crtp_univ_prior_approx_model_namespace::hier_crtp_univ_prior_approx_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 12;
      context__.validate_dims("data initialization", "N_crtp", "int",
        std::vector<size_t>{});
      N_crtp = std::numeric_limits<int>::min();
      current_statement__ = 12;
      N_crtp = context__.vals_i("N_crtp")[(1 - 1)];
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "N_crtp", N_crtp, 1);
      current_statement__ = 13;
      stan::math::validate_non_negative_index("t_crtp", "N_crtp", N_crtp);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "t_crtp", "double",
        std::vector<size_t>{static_cast<size_t>(N_crtp)});
      t_crtp_data__ = Eigen::Matrix<double,-1,1>::Constant(N_crtp,
                        std::numeric_limits<double>::quiet_NaN());
      new (&t_crtp)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(t_crtp_data__.data(), N_crtp);
      {
        std::vector<local_scalar_t__> t_crtp_flat__;
        current_statement__ = 14;
        t_crtp_flat__ = context__.vals_r("t_crtp");
        current_statement__ = 14;
        pos__ = 1;
        current_statement__ = 14;
        for (int sym1__ = 1; sym1__ <= N_crtp; ++sym1__) {
          current_statement__ = 14;
          stan::model::assign(t_crtp, t_crtp_flat__[(pos__ - 1)],
            "assigning variable t_crtp", stan::model::index_uni(sym1__));
          current_statement__ = 14;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 15;
      stan::math::validate_non_negative_index("scaledRI_crtp", "N_crtp",
        N_crtp);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "scaledRI_crtp",
        "double", std::vector<size_t>{static_cast<size_t>(N_crtp)});
      scaledRI_crtp_data__ = Eigen::Matrix<double,-1,1>::Constant(N_crtp,
                               std::numeric_limits<double>::quiet_NaN());
      new (&scaledRI_crtp)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scaledRI_crtp_data__.data(),
        N_crtp);
      {
        std::vector<local_scalar_t__> scaledRI_crtp_flat__;
        current_statement__ = 16;
        scaledRI_crtp_flat__ = context__.vals_r("scaledRI_crtp");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= N_crtp; ++sym1__) {
          current_statement__ = 16;
          stan::model::assign(scaledRI_crtp, scaledRI_crtp_flat__[(pos__ -
            1)], "assigning variable scaledRI_crtp",
            stan::model::index_uni(sym1__));
          current_statement__ = 16;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 17;
      context__.validate_dims("data initialization", "prior_mean_t0",
        "double", std::vector<size_t>{});
      prior_mean_t0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 17;
      prior_mean_t0 = context__.vals_r("prior_mean_t0")[(1 - 1)];
      current_statement__ = 18;
      context__.validate_dims("data initialization", "prior_sd_t0", "double",
        std::vector<size_t>{});
      prior_sd_t0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 18;
      prior_sd_t0 = context__.vals_r("prior_sd_t0")[(1 - 1)];
      current_statement__ = 19;
      context__.validate_dims("data initialization", "prior_mean_k",
        "double", std::vector<size_t>{});
      prior_mean_k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 19;
      prior_mean_k = context__.vals_r("prior_mean_k")[(1 - 1)];
      current_statement__ = 20;
      context__.validate_dims("data initialization", "prior_sd_k", "double",
        std::vector<size_t>{});
      prior_sd_k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 20;
      prior_sd_k = context__.vals_r("prior_sd_k")[(1 - 1)];
      current_statement__ = 21;
      context__.validate_dims("data initialization", "prior_mean_b",
        "double", std::vector<size_t>{});
      prior_mean_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 21;
      prior_mean_b = context__.vals_r("prior_mean_b")[(1 - 1)];
      current_statement__ = 22;
      context__.validate_dims("data initialization", "prior_sd_b", "double",
        std::vector<size_t>{});
      prior_sd_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 22;
      prior_sd_b = context__.vals_r("prior_sd_b")[(1 - 1)];
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "hier_crtp_univ_prior_approx_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = "};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "hier_crtp_univ_prior_approx_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ t0_crtp = DUMMY_VAR__;
      current_statement__ = 1;
      t0_crtp = in__.template read_constrain_lub<local_scalar_t__,
                  jacobian__>(10, 50, lp__);
      local_scalar_t__ k_crtp = DUMMY_VAR__;
      current_statement__ = 2;
      k_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0.01, 0.5, lp__);
      local_scalar_t__ b_crtp = DUMMY_VAR__;
      current_statement__ = 3;
      b_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0.1, 0.6, lp__);
      local_scalar_t__ sigma_scaledRI_crtp = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_scaledRI_crtp = in__.template read_constrain_lb<local_scalar_t__,
                              jacobian__>(0, lp__);
      {
        current_statement__ = 5;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(t0_crtp,
                         prior_mean_t0, prior_sd_t0));
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(k_crtp,
                         prior_mean_k, prior_sd_k));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b_crtp,
                         prior_mean_b, prior_sd_b));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_scaledRI_crtp,
                         0.01, 0.1));
        current_statement__ = 9;
        stan::math::validate_non_negative_index("mu", "N_crtp", N_crtp);
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_crtp, DUMMY_VAR__);
        current_statement__ = 10;
        stan::model::assign(mu,
          stan::math::add(
            stan::math::multiply((1 - b_crtp),
              stan::math::inv_logit(
                stan::math::multiply(k_crtp,
                  stan::math::subtract(t_crtp, t0_crtp)))), b_crtp),
          "assigning variable mu");
        current_statement__ = 11;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(scaledRI_crtp, mu,
                         sigma_scaledRI_crtp));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "hier_crtp_univ_prior_approx_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double t0_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      t0_crtp = in__.template read_constrain_lub<local_scalar_t__,
                  jacobian__>(10, 50, lp__);
      double k_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      k_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0.01, 0.5, lp__);
      double b_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      b_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0.1, 0.6, lp__);
      double sigma_scaledRI_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma_scaledRI_crtp = in__.template read_constrain_lb<local_scalar_t__,
                              jacobian__>(0, lp__);
      out__.write(t0_crtp);
      out__.write(k_crtp);
      out__.write(b_crtp);
      out__.write(sigma_scaledRI_crtp);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ t0_crtp = DUMMY_VAR__;
      current_statement__ = 1;
      t0_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lub(10, 50, t0_crtp);
      local_scalar_t__ k_crtp = DUMMY_VAR__;
      current_statement__ = 2;
      k_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lub(0.01, 0.5, k_crtp);
      local_scalar_t__ b_crtp = DUMMY_VAR__;
      current_statement__ = 3;
      b_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lub(0.1, 0.6, b_crtp);
      local_scalar_t__ sigma_scaledRI_crtp = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_scaledRI_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_scaledRI_crtp);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "t0_crtp",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "k_crtp", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "b_crtp", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization",
        "sigma_scaledRI_crtp", "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ t0_crtp = DUMMY_VAR__;
      current_statement__ = 1;
      t0_crtp = context__.vals_r("t0_crtp")[(1 - 1)];
      out__.write_free_lub(10, 50, t0_crtp);
      local_scalar_t__ k_crtp = DUMMY_VAR__;
      current_statement__ = 2;
      k_crtp = context__.vals_r("k_crtp")[(1 - 1)];
      out__.write_free_lub(0.01, 0.5, k_crtp);
      local_scalar_t__ b_crtp = DUMMY_VAR__;
      current_statement__ = 3;
      b_crtp = context__.vals_r("b_crtp")[(1 - 1)];
      out__.write_free_lub(0.1, 0.6, b_crtp);
      local_scalar_t__ sigma_scaledRI_crtp = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_scaledRI_crtp = context__.vals_r("sigma_scaledRI_crtp")[(1 - 1)];
      out__.write_free_lb(0, sigma_scaledRI_crtp);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"t0_crtp", "k_crtp", "b_crtp",
                "sigma_scaledRI_crtp"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "t0_crtp");
    param_names__.emplace_back(std::string() + "k_crtp");
    param_names__.emplace_back(std::string() + "b_crtp");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_crtp");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "t0_crtp");
    param_names__.emplace_back(std::string() + "k_crtp");
    param_names__.emplace_back(std::string() + "b_crtp");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_crtp");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"t0_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"t0_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = hier_crtp_univ_prior_approx_model_namespace::hier_crtp_univ_prior_approx_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return hier_crtp_univ_prior_approx_model_namespace::profiles__;
}
#endif