// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace invT_logistic_fixed_multiv_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 39> locations_array__ =
  {" (found before start of program)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 26, column 2 to column 30)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 31, column 4 to column 54)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 33, column 11 to column 21)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 33, column 4 to line 35, column 13)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 38, column 6 to column 65)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 37, column 4 to line 38, column 65)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 41, column 6 to column 49)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 40, column 4 to line 41, column 49)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 43, column 4 to column 63)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 30, column 17 to line 44, column 3)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 30, column 2 to line 44, column 3)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 3, column 2 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 4, column 9 to column 19)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 4, column 2 to column 39)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 5, column 9 to column 19)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 5, column 2 to column 32)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 6, column 2 to column 21)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 9, column 2 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 10, column 9 to column 10)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 10, column 2 to column 15)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 11, column 9 to column 10)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 11, column 2 to column 14)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 12, column 9 to column 10)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 12, column 2 to column 14)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 13, column 9 to column 10)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 13, column 2 to column 27)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 16, column 9 to column 19)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 16, column 2 to column 42)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 17, column 9 to column 10)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 17, column 2 to column 30)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 18, column 2 to column 40)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 20, column 9 to column 19)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 20, column 2 to column 34)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 21, column 9 to column 10)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 21, column 2 to column 22)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 22, column 2 to column 32)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 26, column 9 to column 19)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/invT_logistic_fixed_multiv.stan', line 26, column 21 to column 22)"};
class invT_logistic_fixed_multiv_model final : public model_base_crtp<invT_logistic_fixed_multiv_model> {
 private:
  int N_downcore;
  Eigen::Matrix<double,-1,1> scaledRI_downcore_data__;
  Eigen::Matrix<double,-1,1> prior_mu_t_data__;
  double prior_sigma_t;
  int M;
  Eigen::Matrix<double,-1,1> t0_data__;
  Eigen::Matrix<double,-1,1> k_data__;
  Eigen::Matrix<double,-1,1> b_data__;
  Eigen::Matrix<double,-1,1> sigma_scaledRI_data__;
  Eigen::Matrix<double,-1,1> gdgt23ratio_downcore_data__;
  Eigen::Matrix<double,-1,1> beta0_gdgt23ratio_data__;
  int use_gdgt23ratio;
  Eigen::Matrix<double,-1,1> no3_downcore_data__;
  Eigen::Matrix<double,-1,1> beta0_no3_data__;
  int use_no3;
  Eigen::Map<Eigen::Matrix<double,-1,1>> scaledRI_downcore{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_mu_t{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> t0{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> k{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> b{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> sigma_scaledRI{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> gdgt23ratio_downcore{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> beta0_gdgt23ratio{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> no3_downcore{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> beta0_no3{nullptr, 0};
 public:
  ~invT_logistic_fixed_multiv_model() {}
  invT_logistic_fixed_multiv_model(stan::io::var_context& context__,
                                   unsigned int random_seed__ = 0,
                                   std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "invT_logistic_fixed_multiv_model_namespace::invT_logistic_fixed_multiv_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 12;
      context__.validate_dims("data initialization", "N_downcore", "int",
        std::vector<size_t>{});
      N_downcore = std::numeric_limits<int>::min();
      current_statement__ = 12;
      N_downcore = context__.vals_i("N_downcore")[(1 - 1)];
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "N_downcore",
        N_downcore, 1);
      current_statement__ = 13;
      stan::math::validate_non_negative_index("scaledRI_downcore",
        "N_downcore", N_downcore);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "scaledRI_downcore",
        "double", std::vector<size_t>{static_cast<size_t>(N_downcore)});
      scaledRI_downcore_data__ = Eigen::Matrix<double,-1,1>::Constant(N_downcore,
                                   std::numeric_limits<double>::quiet_NaN());
      new (&scaledRI_downcore)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scaledRI_downcore_data__.data(),
        N_downcore);
      {
        std::vector<local_scalar_t__> scaledRI_downcore_flat__;
        current_statement__ = 14;
        scaledRI_downcore_flat__ = context__.vals_r("scaledRI_downcore");
        current_statement__ = 14;
        pos__ = 1;
        current_statement__ = 14;
        for (int sym1__ = 1; sym1__ <= N_downcore; ++sym1__) {
          current_statement__ = 14;
          stan::model::assign(scaledRI_downcore,
            scaledRI_downcore_flat__[(pos__ - 1)],
            "assigning variable scaledRI_downcore",
            stan::model::index_uni(sym1__));
          current_statement__ = 14;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 15;
      stan::math::validate_non_negative_index("prior_mu_t", "N_downcore",
        N_downcore);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "prior_mu_t", "double",
        std::vector<size_t>{static_cast<size_t>(N_downcore)});
      prior_mu_t_data__ = Eigen::Matrix<double,-1,1>::Constant(N_downcore,
                            std::numeric_limits<double>::quiet_NaN());
      new (&prior_mu_t)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_mu_t_data__.data(),
        N_downcore);
      {
        std::vector<local_scalar_t__> prior_mu_t_flat__;
        current_statement__ = 16;
        prior_mu_t_flat__ = context__.vals_r("prior_mu_t");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= N_downcore; ++sym1__) {
          current_statement__ = 16;
          stan::model::assign(prior_mu_t, prior_mu_t_flat__[(pos__ - 1)],
            "assigning variable prior_mu_t", stan::model::index_uni(sym1__));
          current_statement__ = 16;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 17;
      context__.validate_dims("data initialization", "prior_sigma_t",
        "double", std::vector<size_t>{});
      prior_sigma_t = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 17;
      prior_sigma_t = context__.vals_r("prior_sigma_t")[(1 - 1)];
      current_statement__ = 18;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 18;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "M", M, 1);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("t0", "M", M);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "t0", "double",
        std::vector<size_t>{static_cast<size_t>(M)});
      t0_data__ = Eigen::Matrix<double,-1,1>::Constant(M,
                    std::numeric_limits<double>::quiet_NaN());
      new (&t0) Eigen::Map<Eigen::Matrix<double,-1,1>>(t0_data__.data(), M);
      {
        std::vector<local_scalar_t__> t0_flat__;
        current_statement__ = 20;
        t0_flat__ = context__.vals_r("t0");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 20;
          stan::model::assign(t0, t0_flat__[(pos__ - 1)],
            "assigning variable t0", stan::model::index_uni(sym1__));
          current_statement__ = 20;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      stan::math::validate_non_negative_index("k", "M", M);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "k", "double",
        std::vector<size_t>{static_cast<size_t>(M)});
      k_data__ = Eigen::Matrix<double,-1,1>::Constant(M,
                   std::numeric_limits<double>::quiet_NaN());
      new (&k) Eigen::Map<Eigen::Matrix<double,-1,1>>(k_data__.data(), M);
      {
        std::vector<local_scalar_t__> k_flat__;
        current_statement__ = 22;
        k_flat__ = context__.vals_r("k");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 22;
          stan::model::assign(k, k_flat__[(pos__ - 1)],
            "assigning variable k", stan::model::index_uni(sym1__));
          current_statement__ = 22;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      stan::math::validate_non_negative_index("b", "M", M);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "b", "double",
        std::vector<size_t>{static_cast<size_t>(M)});
      b_data__ = Eigen::Matrix<double,-1,1>::Constant(M,
                   std::numeric_limits<double>::quiet_NaN());
      new (&b) Eigen::Map<Eigen::Matrix<double,-1,1>>(b_data__.data(), M);
      {
        std::vector<local_scalar_t__> b_flat__;
        current_statement__ = 24;
        b_flat__ = context__.vals_r("b");
        current_statement__ = 24;
        pos__ = 1;
        current_statement__ = 24;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 24;
          stan::model::assign(b, b_flat__[(pos__ - 1)],
            "assigning variable b", stan::model::index_uni(sym1__));
          current_statement__ = 24;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 25;
      stan::math::validate_non_negative_index("sigma_scaledRI", "M", M);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "sigma_scaledRI",
        "double", std::vector<size_t>{static_cast<size_t>(M)});
      sigma_scaledRI_data__ = Eigen::Matrix<double,-1,1>::Constant(M,
                                std::numeric_limits<double>::quiet_NaN());
      new (&sigma_scaledRI)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(sigma_scaledRI_data__.data(),
        M);
      {
        std::vector<local_scalar_t__> sigma_scaledRI_flat__;
        current_statement__ = 26;
        sigma_scaledRI_flat__ = context__.vals_r("sigma_scaledRI");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 26;
          stan::model::assign(sigma_scaledRI, sigma_scaledRI_flat__[(pos__ -
            1)], "assigning variable sigma_scaledRI",
            stan::model::index_uni(sym1__));
          current_statement__ = 26;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 27;
      stan::math::validate_non_negative_index("gdgt23ratio_downcore",
        "N_downcore", N_downcore);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "gdgt23ratio_downcore",
        "double", std::vector<size_t>{static_cast<size_t>(N_downcore)});
      gdgt23ratio_downcore_data__ = Eigen::Matrix<double,-1,1>::Constant(N_downcore,
                                      std::numeric_limits<double>::quiet_NaN());
      new (&gdgt23ratio_downcore)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(gdgt23ratio_downcore_data__.data(),
        N_downcore);
      {
        std::vector<local_scalar_t__> gdgt23ratio_downcore_flat__;
        current_statement__ = 28;
        gdgt23ratio_downcore_flat__ = context__.vals_r("gdgt23ratio_downcore");
        current_statement__ = 28;
        pos__ = 1;
        current_statement__ = 28;
        for (int sym1__ = 1; sym1__ <= N_downcore; ++sym1__) {
          current_statement__ = 28;
          stan::model::assign(gdgt23ratio_downcore,
            gdgt23ratio_downcore_flat__[(pos__ - 1)],
            "assigning variable gdgt23ratio_downcore",
            stan::model::index_uni(sym1__));
          current_statement__ = 28;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 29;
      stan::math::validate_non_negative_index("beta0_gdgt23ratio", "M", M);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "beta0_gdgt23ratio",
        "double", std::vector<size_t>{static_cast<size_t>(M)});
      beta0_gdgt23ratio_data__ = Eigen::Matrix<double,-1,1>::Constant(M,
                                   std::numeric_limits<double>::quiet_NaN());
      new (&beta0_gdgt23ratio)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(beta0_gdgt23ratio_data__.data(),
        M);
      {
        std::vector<local_scalar_t__> beta0_gdgt23ratio_flat__;
        current_statement__ = 30;
        beta0_gdgt23ratio_flat__ = context__.vals_r("beta0_gdgt23ratio");
        current_statement__ = 30;
        pos__ = 1;
        current_statement__ = 30;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 30;
          stan::model::assign(beta0_gdgt23ratio,
            beta0_gdgt23ratio_flat__[(pos__ - 1)],
            "assigning variable beta0_gdgt23ratio",
            stan::model::index_uni(sym1__));
          current_statement__ = 30;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 31;
      context__.validate_dims("data initialization", "use_gdgt23ratio",
        "int", std::vector<size_t>{});
      use_gdgt23ratio = std::numeric_limits<int>::min();
      current_statement__ = 31;
      use_gdgt23ratio = context__.vals_i("use_gdgt23ratio")[(1 - 1)];
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "use_gdgt23ratio",
        use_gdgt23ratio, 0);
      current_statement__ = 31;
      stan::math::check_less_or_equal(function__, "use_gdgt23ratio",
        use_gdgt23ratio, 1);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("no3_downcore", "N_downcore",
        N_downcore);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "no3_downcore",
        "double", std::vector<size_t>{static_cast<size_t>(N_downcore)});
      no3_downcore_data__ = Eigen::Matrix<double,-1,1>::Constant(N_downcore,
                              std::numeric_limits<double>::quiet_NaN());
      new (&no3_downcore)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(no3_downcore_data__.data(),
        N_downcore);
      {
        std::vector<local_scalar_t__> no3_downcore_flat__;
        current_statement__ = 33;
        no3_downcore_flat__ = context__.vals_r("no3_downcore");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= N_downcore; ++sym1__) {
          current_statement__ = 33;
          stan::model::assign(no3_downcore, no3_downcore_flat__[(pos__ - 1)],
            "assigning variable no3_downcore", stan::model::index_uni(sym1__));
          current_statement__ = 33;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("beta0_no3", "M", M);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "beta0_no3", "double",
        std::vector<size_t>{static_cast<size_t>(M)});
      beta0_no3_data__ = Eigen::Matrix<double,-1,1>::Constant(M,
                           std::numeric_limits<double>::quiet_NaN());
      new (&beta0_no3)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(beta0_no3_data__.data(), M);
      {
        std::vector<local_scalar_t__> beta0_no3_flat__;
        current_statement__ = 35;
        beta0_no3_flat__ = context__.vals_r("beta0_no3");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 35;
          stan::model::assign(beta0_no3, beta0_no3_flat__[(pos__ - 1)],
            "assigning variable beta0_no3", stan::model::index_uni(sym1__));
          current_statement__ = 35;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 36;
      context__.validate_dims("data initialization", "use_no3", "int",
        std::vector<size_t>{});
      use_no3 = std::numeric_limits<int>::min();
      current_statement__ = 36;
      use_no3 = context__.vals_i("use_no3")[(1 - 1)];
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "use_no3", use_no3, 0);
      current_statement__ = 36;
      stan::math::check_less_or_equal(function__, "use_no3", use_no3, 1);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("t_est", "N_downcore",
        N_downcore);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("t_est", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (N_downcore * M);
  }
  inline std::string model_name() const final {
    return "invT_logistic_fixed_multiv_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = "};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "invT_logistic_fixed_multiv_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> t_est =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_downcore, M,
          DUMMY_VAR__);
      current_statement__ = 1;
      t_est = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,-1>>(N_downcore, M);
      {
        current_statement__ = 11;
        for (int m = 1; m <= M; ++m) {
          current_statement__ = 2;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::math::col(t_est, m), prior_mu_t,
                           prior_sigma_t));
          current_statement__ = 3;
          stan::math::validate_non_negative_index("mu_scaledRI",
            "N_downcore", N_downcore);
          Eigen::Matrix<local_scalar_t__,-1,1> mu_scaledRI =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_downcore,
              DUMMY_VAR__);
          current_statement__ = 4;
          stan::model::assign(mu_scaledRI,
            stan::math::add(
              stan::math::multiply((1 -
                stan::model::rvalue(b, "b", stan::model::index_uni(m))),
                stan::math::inv_logit(
                  stan::math::multiply(
                    stan::model::rvalue(k, "k", stan::model::index_uni(m)),
                    stan::math::subtract(stan::math::col(t_est, m),
                      stan::model::rvalue(t0, "t0", stan::model::index_uni(m)))))),
              stan::model::rvalue(b, "b", stan::model::index_uni(m))),
            "assigning variable mu_scaledRI");
          current_statement__ = 6;
          if (stan::math::logical_eq(use_gdgt23ratio, 1)) {
            current_statement__ = 5;
            stan::model::assign(mu_scaledRI,
              stan::math::add(stan::model::deep_copy(mu_scaledRI),
                stan::math::multiply(
                  stan::model::rvalue(beta0_gdgt23ratio, "beta0_gdgt23ratio",
                    stan::model::index_uni(m)), gdgt23ratio_downcore)),
              "assigning variable mu_scaledRI");
          }
          current_statement__ = 8;
          if (stan::math::logical_eq(use_no3, 1)) {
            current_statement__ = 7;
            stan::model::assign(mu_scaledRI,
              stan::math::add(stan::model::deep_copy(mu_scaledRI),
                stan::math::multiply(
                  stan::model::rvalue(beta0_no3, "beta0_no3",
                    stan::model::index_uni(m)), no3_downcore)),
              "assigning variable mu_scaledRI");
          }
          current_statement__ = 9;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(scaledRI_downcore,
                           mu_scaledRI,
                           stan::model::rvalue(sigma_scaledRI,
                             "sigma_scaledRI", stan::model::index_uni(m))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "invT_logistic_fixed_multiv_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,-1> t_est =
        Eigen::Matrix<double,-1,-1>::Constant(N_downcore, M,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      t_est = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,-1>>(N_downcore, M);
      out__.write(t_est);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> t_est =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_downcore, M,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(t_est,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N_downcore, M),
        "assigning variable t_est");
      out__.write(t_est);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "t_est", "double",
        std::vector<size_t>{static_cast<size_t>(N_downcore),
          static_cast<size_t>(M)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> t_est =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_downcore, M,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> t_est_flat__;
        current_statement__ = 1;
        t_est_flat__ = context__.vals_r("t_est");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= N_downcore; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(t_est, t_est_flat__[(pos__ - 1)],
              "assigning variable t_est", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(t_est);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"t_est"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    N_downcore),
                                                 static_cast<size_t>(M)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N_downcore; ++sym2__) {
        param_names__.emplace_back(std::string() + "t_est" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N_downcore; ++sym2__) {
        param_names__.emplace_back(std::string() + "t_est" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"t_est\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_downcore) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"t_est\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_downcore) + ",\"cols\":" + std::to_string(M) + "},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (N_downcore * M);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (N_downcore * M);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = invT_logistic_fixed_multiv_model_namespace::invT_logistic_fixed_multiv_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return invT_logistic_fixed_multiv_model_namespace::profiles__;
}
#endif