// Code generated by stanc v2.36.0
#include <stan/model/model_header.hpp>
namespace invT_logistic_fixed_univ_meanprior_bayes_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 30> locations_array__ =
  {" (found before start of program)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 21, column 2 to column 30)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 23, column 2 to column 31)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 24, column 2 to column 18)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 25, column 2 to column 27)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 26, column 2 to column 31)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 31, column 2 to column 29)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 32, column 2 to column 27)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 33, column 2 to column 27)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 34, column 2 to column 65)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 36, column 9 to column 10)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 36, column 2 to column 24)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 37, column 2 to column 44)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 38, column 2 to column 58)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 39, column 2 to column 49)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 2, column 2 to column 17)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 3, column 9 to column 10)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 3, column 2 to column 21)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 4, column 9 to column 10)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 4, column 2 to column 23)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 5, column 2 to column 21)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 8, column 2 to column 13)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 9, column 2 to column 12)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 10, column 2 to column 12)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 11, column 2 to column 25)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 14, column 2 to column 14)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 15, column 2 to column 13)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 16, column 2 to column 13)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 17, column 2 to column 26)",
  " (in 'invT_logistic_fixed_univ_meanprior_bayes.stan', line 21, column 21 to column 22)"};
class invT_logistic_fixed_univ_meanprior_bayes_model final : public model_base_crtp<invT_logistic_fixed_univ_meanprior_bayes_model> {
 private:
  int N;
  Eigen::Matrix<double,-1,1> scaledRI_data__;
  Eigen::Matrix<double,-1,1> prior_mu_t_data__;
  double prior_sigma_t;
  double mu_t0;
  double mu_k;
  double mu_b;
  double mu_sigma_scaledRI;
  double std_t0;
  double std_k;
  double std_b;
  double std_sigma_scaledRI;
  Eigen::Map<Eigen::Matrix<double,-1,1>> scaledRI{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_mu_t{nullptr, 0};
 public:
  ~invT_logistic_fixed_univ_meanprior_bayes_model() {}
  invT_logistic_fixed_univ_meanprior_bayes_model(stan::io::var_context&
                                                 context__, unsigned int
                                                 random_seed__ = 0,
                                                 std::ostream*
                                                 pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "invT_logistic_fixed_univ_meanprior_bayes_model_namespace::invT_logistic_fixed_univ_meanprior_bayes_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 15;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 15;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 16;
      stan::math::validate_non_negative_index("scaledRI", "N", N);
      current_statement__ = 17;
      context__.validate_dims("data initialization", "scaledRI", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      scaledRI_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                          std::numeric_limits<double>::quiet_NaN());
      new (&scaledRI)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scaledRI_data__.data(), N);
      {
        std::vector<local_scalar_t__> scaledRI_flat__;
        current_statement__ = 17;
        scaledRI_flat__ = context__.vals_r("scaledRI");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(scaledRI, scaledRI_flat__[(pos__ - 1)],
            "assigning variable scaledRI", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 18;
      stan::math::validate_non_negative_index("prior_mu_t", "N", N);
      current_statement__ = 19;
      context__.validate_dims("data initialization", "prior_mu_t", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      prior_mu_t_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                            std::numeric_limits<double>::quiet_NaN());
      new (&prior_mu_t)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_mu_t_data__.data(), N);
      {
        std::vector<local_scalar_t__> prior_mu_t_flat__;
        current_statement__ = 19;
        prior_mu_t_flat__ = context__.vals_r("prior_mu_t");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(prior_mu_t, prior_mu_t_flat__[(pos__ - 1)],
            "assigning variable prior_mu_t", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 20;
      context__.validate_dims("data initialization", "prior_sigma_t",
        "double", std::vector<size_t>{});
      prior_sigma_t = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 20;
      prior_sigma_t = context__.vals_r("prior_sigma_t")[(1 - 1)];
      current_statement__ = 21;
      context__.validate_dims("data initialization", "mu_t0", "double",
        std::vector<size_t>{});
      mu_t0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 21;
      mu_t0 = context__.vals_r("mu_t0")[(1 - 1)];
      current_statement__ = 22;
      context__.validate_dims("data initialization", "mu_k", "double",
        std::vector<size_t>{});
      mu_k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 22;
      mu_k = context__.vals_r("mu_k")[(1 - 1)];
      current_statement__ = 23;
      context__.validate_dims("data initialization", "mu_b", "double",
        std::vector<size_t>{});
      mu_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 23;
      mu_b = context__.vals_r("mu_b")[(1 - 1)];
      current_statement__ = 24;
      context__.validate_dims("data initialization", "mu_sigma_scaledRI",
        "double", std::vector<size_t>{});
      mu_sigma_scaledRI = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 24;
      mu_sigma_scaledRI = context__.vals_r("mu_sigma_scaledRI")[(1 - 1)];
      current_statement__ = 25;
      context__.validate_dims("data initialization", "std_t0", "double",
        std::vector<size_t>{});
      std_t0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 25;
      std_t0 = context__.vals_r("std_t0")[(1 - 1)];
      current_statement__ = 26;
      context__.validate_dims("data initialization", "std_k", "double",
        std::vector<size_t>{});
      std_k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 26;
      std_k = context__.vals_r("std_k")[(1 - 1)];
      current_statement__ = 27;
      context__.validate_dims("data initialization", "std_b", "double",
        std::vector<size_t>{});
      std_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 27;
      std_b = context__.vals_r("std_b")[(1 - 1)];
      current_statement__ = 28;
      context__.validate_dims("data initialization", "std_sigma_scaledRI",
        "double", std::vector<size_t>{});
      std_sigma_scaledRI = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 28;
      std_sigma_scaledRI = context__.vals_r("std_sigma_scaledRI")[(1 - 1)];
      current_statement__ = 29;
      stan::math::validate_non_negative_index("t_est", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = N + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "invT_logistic_fixed_univ_meanprior_bayes_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.36.0",
             "stancflags = --filename-in-msg=invT_logistic_fixed_univ_meanprior_bayes.stan"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "invT_logistic_fixed_univ_meanprior_bayes_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto t_est =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(-(1.8), lp__, N);
      current_statement__ = 2;
      auto t0 =
        in__.template read_constrain_lub<local_scalar_t__, jacobian__>(-(5),
          100, lp__);
      current_statement__ = 3;
      auto k =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 4;
      auto b =
        in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0, 1,
          lp__);
      current_statement__ = 5;
      auto sigma_scaledRI =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      {
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(t0, mu_t0, std_t0));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(k, mu_k, std_k));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b, mu_b, std_b));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_scaledRI,
                         mu_sigma_scaledRI, std_sigma_scaledRI));
        current_statement__ = 10;
        stan::math::validate_non_negative_index("mu_scaledRI", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> mu_scaledRI =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(t_est, prior_mu_t,
                         prior_sigma_t));
        current_statement__ = 13;
        stan::model::assign(mu_scaledRI,
          stan::math::add(
            stan::math::multiply((1 - b),
              stan::math::inv_logit(
                stan::math::multiply(k, stan::math::subtract(t_est, t0)))), b),
          "assigning variable mu_scaledRI");
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(scaledRI,
                         mu_scaledRI, sigma_scaledRI));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "invT_logistic_fixed_univ_meanprior_bayes_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto t_est =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(-(1.8), lp__, N);
      current_statement__ = 2;
      auto t0 =
        in__.template read_constrain_lub<local_scalar_t__, jacobian__>(-(5),
          100, lp__);
      current_statement__ = 3;
      auto k =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 4;
      auto b =
        in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0, 1,
          lp__);
      current_statement__ = 5;
      auto sigma_scaledRI =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      {
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(t0, mu_t0, std_t0));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(k, mu_k, std_k));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b, mu_b, std_b));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_scaledRI,
                         mu_sigma_scaledRI, std_sigma_scaledRI));
        current_statement__ = 10;
        stan::math::validate_non_negative_index("mu_scaledRI", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> mu_scaledRI =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(t_est, prior_mu_t,
                         prior_sigma_t));
        current_statement__ = 13;
        stan::model::assign(mu_scaledRI,
          stan::math::add(
            stan::math::multiply((1 - b),
              stan::math::inv_logit(
                stan::math::multiply(k, stan::math::subtract(t_est, t0)))), b),
          "assigning variable mu_scaledRI");
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(scaledRI,
                         mu_scaledRI, sigma_scaledRI));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "invT_logistic_fixed_univ_meanprior_bayes_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto t_est =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(-(1.8), lp__, N);
      current_statement__ = 2;
      auto t0 =
        in__.template read_constrain_lub<local_scalar_t__, jacobian__>(-(5),
          100, lp__);
      current_statement__ = 3;
      auto k =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 4;
      auto b =
        in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0, 1,
          lp__);
      current_statement__ = 5;
      auto sigma_scaledRI =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      out__.write(t_est);
      out__.write(t0);
      out__.write(k);
      out__.write(b);
      out__.write(sigma_scaledRI);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> t_est =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(t_est,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable t_est");
      out__.write_free_lb(-(1.8), t_est);
      local_scalar_t__ t0 = DUMMY_VAR__;
      current_statement__ = 2;
      t0 = in__.read<local_scalar_t__>();
      out__.write_free_lub(-(5), 100, t0);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 3;
      k = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, k);
      local_scalar_t__ b = DUMMY_VAR__;
      current_statement__ = 4;
      b = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, b);
      local_scalar_t__ sigma_scaledRI = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_scaledRI = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_scaledRI);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "t_est", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "t0", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "k", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "b", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sigma_scaledRI",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> t_est =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> t_est_flat__;
        current_statement__ = 1;
        t_est_flat__ = context__.vals_r("t_est");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(t_est, t_est_flat__[(pos__ - 1)],
            "assigning variable t_est", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(-(1.8), t_est);
      local_scalar_t__ t0 = DUMMY_VAR__;
      current_statement__ = 2;
      t0 = context__.vals_r("t0")[(1 - 1)];
      out__.write_free_lub(-(5), 100, t0);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 3;
      k = context__.vals_r("k")[(1 - 1)];
      out__.write_free_lb(0, k);
      local_scalar_t__ b = DUMMY_VAR__;
      current_statement__ = 4;
      b = context__.vals_r("b")[(1 - 1)];
      out__.write_free_lub(0, 1, b);
      local_scalar_t__ sigma_scaledRI = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_scaledRI = context__.vals_r("sigma_scaledRI")[(1 - 1)];
      out__.write_free_lb(0, sigma_scaledRI);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"t_est", "t0", "k", "b",
                "sigma_scaledRI"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(N)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "t_est" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "t0");
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "b");
    param_names__.emplace_back(std::string() + "sigma_scaledRI");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "t_est" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "t0");
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "b");
    param_names__.emplace_back(std::string() + "sigma_scaledRI");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"t_est\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"t0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"t_est\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"t0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((N + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((N + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = invT_logistic_fixed_univ_meanprior_bayes_model_namespace::invT_logistic_fixed_univ_meanprior_bayes_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return invT_logistic_fixed_univ_meanprior_bayes_model_namespace::profiles__;
}
#endif