// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace jnt_cul_meso_hier_crtp_multiv_archive_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 68> locations_array__ =
  {" (found before start of program)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 27, column 4 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 28, column 4 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 29, column 4 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 32, column 4 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 33, column 4 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 34, column 4 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 35, column 4 to column 50)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 36, column 4 to column 42)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 39, column 4 to column 42)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 40, column 4 to column 41)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 41, column 4 to column 41)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 44, column 4 to column 44)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 45, column 4 to column 45)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 46, column 4 to column 45)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 52, column 4 to column 45)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 52, column 38 to column 41)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 53, column 4 to column 31)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 54, column 4 to column 31)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 57, column 4 to column 40)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 58, column 4 to column 40)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 59, column 4 to column 40)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 62, column 4 to column 43)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 63, column 4 to column 44)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 66, column 11 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 66, column 4 to column 116)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 67, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 67, column 4 to column 119)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 69, column 4 to column 63)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 70, column 4 to column 66)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 73, column 4 to column 52)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 74, column 4 to column 50)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 75, column 4 to column 50)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 76, column 4 to column 45)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 77, column 4 to column 37)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 80, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 80, column 4 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 82, column 8 to column 95)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 83, column 8 to column 44)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 86, column 12 to column 80)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 85, column 8 to line 86, column 80)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 89, column 12 to column 71)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 88, column 8 to line 89, column 71)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 81, column 24 to line 90, column 5)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 81, column 4 to line 90, column 5)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 92, column 4 to column 44)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 93, column 4 to column 66)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 3, column 4 to column 23)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 4, column 11 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 4, column 4 to column 24)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 5, column 11 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 5, column 4 to column 31)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 8, column 4 to column 24)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 9, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 9, column 4 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 10, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 10, column 4 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 13, column 4 to column 24)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 14, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 14, column 4 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 15, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 15, column 4 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 18, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 18, column 4 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 19, column 4 to column 42)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 21, column 11 to column 17)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 21, column 4 to column 28)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/jnt_cul_meso_hier_crtp_multiv_archive.stan', line 22, column 4 to column 34)"};
class jnt_cul_meso_hier_crtp_multiv_archive_model final : public model_base_crtp<jnt_cul_meso_hier_crtp_multiv_archive_model> {
 private:
  int N_cul;
  Eigen::Matrix<double,-1,1> t_cul_data__;
  Eigen::Matrix<double,-1,1> scaledRI_cul_data__;
  int N_meso;
  Eigen::Matrix<double,-1,1> t_meso_data__;
  Eigen::Matrix<double,-1,1> scaledRI_meso_data__;
  int N_crtp;
  Eigen::Matrix<double,-1,1> t_crtp_data__;
  Eigen::Matrix<double,-1,1> scaledRI_crtp_data__;
  Eigen::Matrix<double,-1,1> gdgt23ratio_crtp_data__;
  int use_gdgt23ratio;
  Eigen::Matrix<double,-1,1> no3_crtp_data__;
  int use_no3;
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_cul{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> scaledRI_cul{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_meso{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> scaledRI_meso{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_crtp{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> scaledRI_crtp{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> gdgt23ratio_crtp{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> no3_crtp{nullptr, 0};
 public:
  ~jnt_cul_meso_hier_crtp_multiv_archive_model() {}
  jnt_cul_meso_hier_crtp_multiv_archive_model(stan::io::var_context&
                                              context__, unsigned int
                                              random_seed__ = 0,
                                              std::ostream*
                                              pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "jnt_cul_meso_hier_crtp_multiv_archive_model_namespace::jnt_cul_meso_hier_crtp_multiv_archive_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 47;
      context__.validate_dims("data initialization", "N_cul", "int",
        std::vector<size_t>{});
      N_cul = std::numeric_limits<int>::min();
      current_statement__ = 47;
      N_cul = context__.vals_i("N_cul")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "N_cul", N_cul, 1);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("t_cul", "N_cul", N_cul);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "t_cul", "double",
        std::vector<size_t>{static_cast<size_t>(N_cul)});
      t_cul_data__ = Eigen::Matrix<double,-1,1>::Constant(N_cul,
                       std::numeric_limits<double>::quiet_NaN());
      new (&t_cul)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(t_cul_data__.data(), N_cul);
      {
        std::vector<local_scalar_t__> t_cul_flat__;
        current_statement__ = 49;
        t_cul_flat__ = context__.vals_r("t_cul");
        current_statement__ = 49;
        pos__ = 1;
        current_statement__ = 49;
        for (int sym1__ = 1; sym1__ <= N_cul; ++sym1__) {
          current_statement__ = 49;
          stan::model::assign(t_cul, t_cul_flat__[(pos__ - 1)],
            "assigning variable t_cul", stan::model::index_uni(sym1__));
          current_statement__ = 49;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 50;
      stan::math::validate_non_negative_index("scaledRI_cul", "N_cul", N_cul);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "scaledRI_cul",
        "double", std::vector<size_t>{static_cast<size_t>(N_cul)});
      scaledRI_cul_data__ = Eigen::Matrix<double,-1,1>::Constant(N_cul,
                              std::numeric_limits<double>::quiet_NaN());
      new (&scaledRI_cul)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scaledRI_cul_data__.data(),
        N_cul);
      {
        std::vector<local_scalar_t__> scaledRI_cul_flat__;
        current_statement__ = 51;
        scaledRI_cul_flat__ = context__.vals_r("scaledRI_cul");
        current_statement__ = 51;
        pos__ = 1;
        current_statement__ = 51;
        for (int sym1__ = 1; sym1__ <= N_cul; ++sym1__) {
          current_statement__ = 51;
          stan::model::assign(scaledRI_cul, scaledRI_cul_flat__[(pos__ - 1)],
            "assigning variable scaledRI_cul", stan::model::index_uni(sym1__));
          current_statement__ = 51;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 52;
      context__.validate_dims("data initialization", "N_meso", "int",
        std::vector<size_t>{});
      N_meso = std::numeric_limits<int>::min();
      current_statement__ = 52;
      N_meso = context__.vals_i("N_meso")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "N_meso", N_meso, 1);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("t_meso", "N_meso", N_meso);
      current_statement__ = 54;
      context__.validate_dims("data initialization", "t_meso", "double",
        std::vector<size_t>{static_cast<size_t>(N_meso)});
      t_meso_data__ = Eigen::Matrix<double,-1,1>::Constant(N_meso,
                        std::numeric_limits<double>::quiet_NaN());
      new (&t_meso)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(t_meso_data__.data(), N_meso);
      {
        std::vector<local_scalar_t__> t_meso_flat__;
        current_statement__ = 54;
        t_meso_flat__ = context__.vals_r("t_meso");
        current_statement__ = 54;
        pos__ = 1;
        current_statement__ = 54;
        for (int sym1__ = 1; sym1__ <= N_meso; ++sym1__) {
          current_statement__ = 54;
          stan::model::assign(t_meso, t_meso_flat__[(pos__ - 1)],
            "assigning variable t_meso", stan::model::index_uni(sym1__));
          current_statement__ = 54;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 55;
      stan::math::validate_non_negative_index("scaledRI_meso", "N_meso",
        N_meso);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "scaledRI_meso",
        "double", std::vector<size_t>{static_cast<size_t>(N_meso)});
      scaledRI_meso_data__ = Eigen::Matrix<double,-1,1>::Constant(N_meso,
                               std::numeric_limits<double>::quiet_NaN());
      new (&scaledRI_meso)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scaledRI_meso_data__.data(),
        N_meso);
      {
        std::vector<local_scalar_t__> scaledRI_meso_flat__;
        current_statement__ = 56;
        scaledRI_meso_flat__ = context__.vals_r("scaledRI_meso");
        current_statement__ = 56;
        pos__ = 1;
        current_statement__ = 56;
        for (int sym1__ = 1; sym1__ <= N_meso; ++sym1__) {
          current_statement__ = 56;
          stan::model::assign(scaledRI_meso, scaledRI_meso_flat__[(pos__ -
            1)], "assigning variable scaledRI_meso",
            stan::model::index_uni(sym1__));
          current_statement__ = 56;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 57;
      context__.validate_dims("data initialization", "N_crtp", "int",
        std::vector<size_t>{});
      N_crtp = std::numeric_limits<int>::min();
      current_statement__ = 57;
      N_crtp = context__.vals_i("N_crtp")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "N_crtp", N_crtp, 1);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("t_crtp", "N_crtp", N_crtp);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "t_crtp", "double",
        std::vector<size_t>{static_cast<size_t>(N_crtp)});
      t_crtp_data__ = Eigen::Matrix<double,-1,1>::Constant(N_crtp,
                        std::numeric_limits<double>::quiet_NaN());
      new (&t_crtp)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(t_crtp_data__.data(), N_crtp);
      {
        std::vector<local_scalar_t__> t_crtp_flat__;
        current_statement__ = 59;
        t_crtp_flat__ = context__.vals_r("t_crtp");
        current_statement__ = 59;
        pos__ = 1;
        current_statement__ = 59;
        for (int sym1__ = 1; sym1__ <= N_crtp; ++sym1__) {
          current_statement__ = 59;
          stan::model::assign(t_crtp, t_crtp_flat__[(pos__ - 1)],
            "assigning variable t_crtp", stan::model::index_uni(sym1__));
          current_statement__ = 59;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 60;
      stan::math::validate_non_negative_index("scaledRI_crtp", "N_crtp",
        N_crtp);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "scaledRI_crtp",
        "double", std::vector<size_t>{static_cast<size_t>(N_crtp)});
      scaledRI_crtp_data__ = Eigen::Matrix<double,-1,1>::Constant(N_crtp,
                               std::numeric_limits<double>::quiet_NaN());
      new (&scaledRI_crtp)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scaledRI_crtp_data__.data(),
        N_crtp);
      {
        std::vector<local_scalar_t__> scaledRI_crtp_flat__;
        current_statement__ = 61;
        scaledRI_crtp_flat__ = context__.vals_r("scaledRI_crtp");
        current_statement__ = 61;
        pos__ = 1;
        current_statement__ = 61;
        for (int sym1__ = 1; sym1__ <= N_crtp; ++sym1__) {
          current_statement__ = 61;
          stan::model::assign(scaledRI_crtp, scaledRI_crtp_flat__[(pos__ -
            1)], "assigning variable scaledRI_crtp",
            stan::model::index_uni(sym1__));
          current_statement__ = 61;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 62;
      stan::math::validate_non_negative_index("gdgt23ratio_crtp", "N_crtp",
        N_crtp);
      current_statement__ = 63;
      context__.validate_dims("data initialization", "gdgt23ratio_crtp",
        "double", std::vector<size_t>{static_cast<size_t>(N_crtp)});
      gdgt23ratio_crtp_data__ = Eigen::Matrix<double,-1,1>::Constant(N_crtp,
                                  std::numeric_limits<double>::quiet_NaN());
      new (&gdgt23ratio_crtp)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(gdgt23ratio_crtp_data__.data(),
        N_crtp);
      {
        std::vector<local_scalar_t__> gdgt23ratio_crtp_flat__;
        current_statement__ = 63;
        gdgt23ratio_crtp_flat__ = context__.vals_r("gdgt23ratio_crtp");
        current_statement__ = 63;
        pos__ = 1;
        current_statement__ = 63;
        for (int sym1__ = 1; sym1__ <= N_crtp; ++sym1__) {
          current_statement__ = 63;
          stan::model::assign(gdgt23ratio_crtp,
            gdgt23ratio_crtp_flat__[(pos__ - 1)],
            "assigning variable gdgt23ratio_crtp",
            stan::model::index_uni(sym1__));
          current_statement__ = 63;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 64;
      context__.validate_dims("data initialization", "use_gdgt23ratio",
        "int", std::vector<size_t>{});
      use_gdgt23ratio = std::numeric_limits<int>::min();
      current_statement__ = 64;
      use_gdgt23ratio = context__.vals_i("use_gdgt23ratio")[(1 - 1)];
      current_statement__ = 64;
      stan::math::check_greater_or_equal(function__, "use_gdgt23ratio",
        use_gdgt23ratio, 0);
      current_statement__ = 64;
      stan::math::check_less_or_equal(function__, "use_gdgt23ratio",
        use_gdgt23ratio, 1);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("no3_crtp", "N_crtp", N_crtp);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "no3_crtp", "double",
        std::vector<size_t>{static_cast<size_t>(N_crtp)});
      no3_crtp_data__ = Eigen::Matrix<double,-1,1>::Constant(N_crtp,
                          std::numeric_limits<double>::quiet_NaN());
      new (&no3_crtp)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(no3_crtp_data__.data(),
        N_crtp);
      {
        std::vector<local_scalar_t__> no3_crtp_flat__;
        current_statement__ = 66;
        no3_crtp_flat__ = context__.vals_r("no3_crtp");
        current_statement__ = 66;
        pos__ = 1;
        current_statement__ = 66;
        for (int sym1__ = 1; sym1__ <= N_crtp; ++sym1__) {
          current_statement__ = 66;
          stan::model::assign(no3_crtp, no3_crtp_flat__[(pos__ - 1)],
            "assigning variable no3_crtp", stan::model::index_uni(sym1__));
          current_statement__ = 66;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 67;
      context__.validate_dims("data initialization", "use_no3", "int",
        std::vector<size_t>{});
      use_no3 = std::numeric_limits<int>::min();
      current_statement__ = 67;
      use_no3 = context__.vals_i("use_no3")[(1 - 1)];
      current_statement__ = 67;
      stan::math::check_greater_or_equal(function__, "use_no3", use_no3, 0);
      current_statement__ = 67;
      stan::math::check_less_or_equal(function__, "use_no3", use_no3, 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "jnt_cul_meso_hier_crtp_multiv_archive_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = "};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "jnt_cul_meso_hier_crtp_multiv_archive_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ t0_culmeso = DUMMY_VAR__;
      current_statement__ = 1;
      t0_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                     jacobian__>(-1.8, lp__);
      local_scalar_t__ k_culmeso = DUMMY_VAR__;
      current_statement__ = 2;
      k_culmeso = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      local_scalar_t__ b_culmeso = DUMMY_VAR__;
      current_statement__ = 3;
      b_culmeso = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      local_scalar_t__ t0_crtp = DUMMY_VAR__;
      current_statement__ = 4;
      t0_crtp = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(-1.8, lp__);
      local_scalar_t__ k_crtp = DUMMY_VAR__;
      current_statement__ = 5;
      k_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      local_scalar_t__ b_crtp = DUMMY_VAR__;
      current_statement__ = 6;
      b_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      local_scalar_t__ beta0_gdgt23ratio_crtp = DUMMY_VAR__;
      current_statement__ = 7;
      beta0_gdgt23ratio_crtp = in__.template read_constrain_lub<
                                 local_scalar_t__, jacobian__>(-1, 0, lp__);
      local_scalar_t__ beta0_no3_crtp = DUMMY_VAR__;
      current_statement__ = 8;
      beta0_no3_crtp = in__.template read_constrain_lub<local_scalar_t__,
                         jacobian__>(-1, 0, lp__);
      local_scalar_t__ sigma_t0_culmeso = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_t0_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      local_scalar_t__ sigma_k_culmeso = DUMMY_VAR__;
      current_statement__ = 10;
      sigma_k_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                          jacobian__>(0, lp__);
      local_scalar_t__ sigma_b_culmeso = DUMMY_VAR__;
      current_statement__ = 11;
      sigma_b_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                          jacobian__>(0, lp__);
      local_scalar_t__ sigma_scaledRI_cul = DUMMY_VAR__;
      current_statement__ = 12;
      sigma_scaledRI_cul = in__.template read_constrain_lb<local_scalar_t__,
                             jacobian__>(0, lp__);
      local_scalar_t__ sigma_scaledRI_meso = DUMMY_VAR__;
      current_statement__ = 13;
      sigma_scaledRI_meso = in__.template read_constrain_lb<local_scalar_t__,
                              jacobian__>(0, lp__);
      local_scalar_t__ sigma_scaledRI_crtp = DUMMY_VAR__;
      current_statement__ = 14;
      sigma_scaledRI_crtp = in__.template read_constrain_lb<local_scalar_t__,
                              jacobian__>(0, lp__);
      {
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(t0_culmeso, 30, 10));
        current_statement__ = 16;
        if (stan::math::logical_lt(t0_culmeso, -1.8)) {
          current_statement__ = 16;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 16;
          lp_accum__.add(-stan::math::normal_lccdf(-1.8, 30, 10));
        }
        current_statement__ = 17;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(k_culmeso, 2, 5));
        current_statement__ = 18;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(b_culmeso, 2, 5));
        current_statement__ = 19;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma_t0_culmeso, 0,
                         1));
        current_statement__ = 20;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma_k_culmeso, 0,
                         1));
        current_statement__ = 21;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma_b_culmeso, 0,
                         1));
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_scaledRI_cul,
                         0.01, 0.1));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_scaledRI_meso,
                         0.01, 0.1));
        current_statement__ = 24;
        stan::math::validate_non_negative_index("mu_scaledRI_cul", "N_cul",
          N_cul);
        Eigen::Matrix<local_scalar_t__,-1,1> mu_scaledRI_cul =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_cul, DUMMY_VAR__);
        current_statement__ = 25;
        stan::model::assign(mu_scaledRI_cul,
          stan::math::add(
            stan::math::multiply((1 - b_culmeso),
              stan::math::inv_logit(
                stan::math::multiply(k_culmeso,
                  stan::math::subtract(t_cul, t0_culmeso)))), b_culmeso),
          "assigning variable mu_scaledRI_cul");
        current_statement__ = 26;
        stan::math::validate_non_negative_index("mu_scaledRI_meso", "N_meso",
          N_meso);
        Eigen::Matrix<local_scalar_t__,-1,1> mu_scaledRI_meso =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_meso, DUMMY_VAR__);
        current_statement__ = 27;
        stan::model::assign(mu_scaledRI_meso,
          stan::math::add(
            stan::math::multiply((1 - b_culmeso),
              stan::math::inv_logit(
                stan::math::multiply(k_culmeso,
                  stan::math::subtract(t_meso, t0_culmeso)))), b_culmeso),
          "assigning variable mu_scaledRI_meso");
        current_statement__ = 28;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(scaledRI_cul,
                         mu_scaledRI_cul, sigma_scaledRI_cul));
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(scaledRI_meso,
                         mu_scaledRI_meso, sigma_scaledRI_meso));
        current_statement__ = 30;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(t0_crtp, t0_culmeso,
                         sigma_t0_culmeso));
        current_statement__ = 31;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(k_crtp, k_culmeso,
                         sigma_k_culmeso));
        current_statement__ = 32;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b_crtp, b_culmeso,
                         sigma_b_culmeso));
        current_statement__ = 33;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         beta0_gdgt23ratio_crtp, 0, 0.05));
        current_statement__ = 34;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta0_no3_crtp, 0,
                         0.05));
        current_statement__ = 35;
        stan::math::validate_non_negative_index("mu_scaledRI_crtp", "N_crtp",
          N_crtp);
        Eigen::Matrix<local_scalar_t__,-1,1> mu_scaledRI_crtp =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_crtp, DUMMY_VAR__);
        current_statement__ = 44;
        for (int i = 1; i <= N_crtp; ++i) {
          local_scalar_t__ base_scaledRI = DUMMY_VAR__;
          current_statement__ = 37;
          base_scaledRI = (((1 - b_crtp) *
            stan::math::inv_logit((k_crtp *
              (stan::model::rvalue(t_crtp, "t_crtp",
                 stan::model::index_uni(i)) - t0_crtp))))
            + b_crtp);
          current_statement__ = 38;
          stan::model::assign(mu_scaledRI_crtp, base_scaledRI,
            "assigning variable mu_scaledRI_crtp", stan::model::index_uni(i));
          current_statement__ = 40;
          if (stan::math::logical_eq(use_gdgt23ratio, 1)) {
            current_statement__ = 39;
            stan::model::assign(mu_scaledRI_crtp,
              (stan::model::rvalue(mu_scaledRI_crtp, "mu_scaledRI_crtp",
                 stan::model::index_uni(i)) + (beta0_gdgt23ratio_crtp *
              stan::model::rvalue(gdgt23ratio_crtp, "gdgt23ratio_crtp",
                stan::model::index_uni(i)))),
              "assigning variable mu_scaledRI_crtp",
              stan::model::index_uni(i));
          }
          current_statement__ = 42;
          if ((stan::math::primitive_value(stan::math::logical_eq(use_no3, 1))
              &&
              stan::math::primitive_value(
                stan::math::logical_lte(
                  stan::model::rvalue(no3_crtp, "no3_crtp",
                    stan::model::index_uni(i)), 2.7)))) {
            current_statement__ = 41;
            stan::model::assign(mu_scaledRI_crtp,
              (stan::model::rvalue(mu_scaledRI_crtp, "mu_scaledRI_crtp",
                 stan::model::index_uni(i)) + (beta0_no3_crtp *
              stan::math::log10(
                stan::model::rvalue(no3_crtp, "no3_crtp",
                  stan::model::index_uni(i))))),
              "assigning variable mu_scaledRI_crtp",
              stan::model::index_uni(i));
          }
        }
        current_statement__ = 45;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_scaledRI_crtp,
                         0.01, 0.1));
        current_statement__ = 46;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(scaledRI_crtp,
                         mu_scaledRI_crtp, sigma_scaledRI_crtp));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "jnt_cul_meso_hier_crtp_multiv_archive_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double t0_culmeso = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      t0_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                     jacobian__>(-1.8, lp__);
      double k_culmeso = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      k_culmeso = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      double b_culmeso = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      b_culmeso = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      double t0_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      t0_crtp = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(-1.8, lp__);
      double k_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      k_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      double b_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      b_crtp = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      double beta0_gdgt23ratio_crtp =
        std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      beta0_gdgt23ratio_crtp = in__.template read_constrain_lub<
                                 local_scalar_t__, jacobian__>(-1, 0, lp__);
      double beta0_no3_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      beta0_no3_crtp = in__.template read_constrain_lub<local_scalar_t__,
                         jacobian__>(-1, 0, lp__);
      double sigma_t0_culmeso = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      sigma_t0_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      double sigma_k_culmeso = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 10;
      sigma_k_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                          jacobian__>(0, lp__);
      double sigma_b_culmeso = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      sigma_b_culmeso = in__.template read_constrain_lb<local_scalar_t__,
                          jacobian__>(0, lp__);
      double sigma_scaledRI_cul = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      sigma_scaledRI_cul = in__.template read_constrain_lb<local_scalar_t__,
                             jacobian__>(0, lp__);
      double sigma_scaledRI_meso = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      sigma_scaledRI_meso = in__.template read_constrain_lb<local_scalar_t__,
                              jacobian__>(0, lp__);
      double sigma_scaledRI_crtp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 14;
      sigma_scaledRI_crtp = in__.template read_constrain_lb<local_scalar_t__,
                              jacobian__>(0, lp__);
      out__.write(t0_culmeso);
      out__.write(k_culmeso);
      out__.write(b_culmeso);
      out__.write(t0_crtp);
      out__.write(k_crtp);
      out__.write(b_crtp);
      out__.write(beta0_gdgt23ratio_crtp);
      out__.write(beta0_no3_crtp);
      out__.write(sigma_t0_culmeso);
      out__.write(sigma_k_culmeso);
      out__.write(sigma_b_culmeso);
      out__.write(sigma_scaledRI_cul);
      out__.write(sigma_scaledRI_meso);
      out__.write(sigma_scaledRI_crtp);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ t0_culmeso = DUMMY_VAR__;
      current_statement__ = 1;
      t0_culmeso = in__.read<local_scalar_t__>();
      out__.write_free_lb(-1.8, t0_culmeso);
      local_scalar_t__ k_culmeso = DUMMY_VAR__;
      current_statement__ = 2;
      k_culmeso = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, k_culmeso);
      local_scalar_t__ b_culmeso = DUMMY_VAR__;
      current_statement__ = 3;
      b_culmeso = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, b_culmeso);
      local_scalar_t__ t0_crtp = DUMMY_VAR__;
      current_statement__ = 4;
      t0_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lb(-1.8, t0_crtp);
      local_scalar_t__ k_crtp = DUMMY_VAR__;
      current_statement__ = 5;
      k_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, k_crtp);
      local_scalar_t__ b_crtp = DUMMY_VAR__;
      current_statement__ = 6;
      b_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, b_crtp);
      local_scalar_t__ beta0_gdgt23ratio_crtp = DUMMY_VAR__;
      current_statement__ = 7;
      beta0_gdgt23ratio_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 0, beta0_gdgt23ratio_crtp);
      local_scalar_t__ beta0_no3_crtp = DUMMY_VAR__;
      current_statement__ = 8;
      beta0_no3_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 0, beta0_no3_crtp);
      local_scalar_t__ sigma_t0_culmeso = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_t0_culmeso = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_t0_culmeso);
      local_scalar_t__ sigma_k_culmeso = DUMMY_VAR__;
      current_statement__ = 10;
      sigma_k_culmeso = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_k_culmeso);
      local_scalar_t__ sigma_b_culmeso = DUMMY_VAR__;
      current_statement__ = 11;
      sigma_b_culmeso = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_b_culmeso);
      local_scalar_t__ sigma_scaledRI_cul = DUMMY_VAR__;
      current_statement__ = 12;
      sigma_scaledRI_cul = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_scaledRI_cul);
      local_scalar_t__ sigma_scaledRI_meso = DUMMY_VAR__;
      current_statement__ = 13;
      sigma_scaledRI_meso = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_scaledRI_meso);
      local_scalar_t__ sigma_scaledRI_crtp = DUMMY_VAR__;
      current_statement__ = 14;
      sigma_scaledRI_crtp = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_scaledRI_crtp);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "t0_culmeso",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "k_culmeso",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "b_culmeso",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "t0_crtp",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "k_crtp", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "b_crtp", "double",
        std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization",
        "beta0_gdgt23ratio_crtp", "double", std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "beta0_no3_crtp",
        "double", std::vector<size_t>{});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "sigma_t0_culmeso",
        "double", std::vector<size_t>{});
      current_statement__ = 10;
      context__.validate_dims("parameter initialization", "sigma_k_culmeso",
        "double", std::vector<size_t>{});
      current_statement__ = 11;
      context__.validate_dims("parameter initialization", "sigma_b_culmeso",
        "double", std::vector<size_t>{});
      current_statement__ = 12;
      context__.validate_dims("parameter initialization",
        "sigma_scaledRI_cul", "double", std::vector<size_t>{});
      current_statement__ = 13;
      context__.validate_dims("parameter initialization",
        "sigma_scaledRI_meso", "double", std::vector<size_t>{});
      current_statement__ = 14;
      context__.validate_dims("parameter initialization",
        "sigma_scaledRI_crtp", "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ t0_culmeso = DUMMY_VAR__;
      current_statement__ = 1;
      t0_culmeso = context__.vals_r("t0_culmeso")[(1 - 1)];
      out__.write_free_lb(-1.8, t0_culmeso);
      local_scalar_t__ k_culmeso = DUMMY_VAR__;
      current_statement__ = 2;
      k_culmeso = context__.vals_r("k_culmeso")[(1 - 1)];
      out__.write_free_lub(0, 1, k_culmeso);
      local_scalar_t__ b_culmeso = DUMMY_VAR__;
      current_statement__ = 3;
      b_culmeso = context__.vals_r("b_culmeso")[(1 - 1)];
      out__.write_free_lub(0, 1, b_culmeso);
      local_scalar_t__ t0_crtp = DUMMY_VAR__;
      current_statement__ = 4;
      t0_crtp = context__.vals_r("t0_crtp")[(1 - 1)];
      out__.write_free_lb(-1.8, t0_crtp);
      local_scalar_t__ k_crtp = DUMMY_VAR__;
      current_statement__ = 5;
      k_crtp = context__.vals_r("k_crtp")[(1 - 1)];
      out__.write_free_lub(0, 1, k_crtp);
      local_scalar_t__ b_crtp = DUMMY_VAR__;
      current_statement__ = 6;
      b_crtp = context__.vals_r("b_crtp")[(1 - 1)];
      out__.write_free_lub(0, 1, b_crtp);
      local_scalar_t__ beta0_gdgt23ratio_crtp = DUMMY_VAR__;
      current_statement__ = 7;
      beta0_gdgt23ratio_crtp = context__.vals_r("beta0_gdgt23ratio_crtp")[(1
        - 1)];
      out__.write_free_lub(-1, 0, beta0_gdgt23ratio_crtp);
      local_scalar_t__ beta0_no3_crtp = DUMMY_VAR__;
      current_statement__ = 8;
      beta0_no3_crtp = context__.vals_r("beta0_no3_crtp")[(1 - 1)];
      out__.write_free_lub(-1, 0, beta0_no3_crtp);
      local_scalar_t__ sigma_t0_culmeso = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_t0_culmeso = context__.vals_r("sigma_t0_culmeso")[(1 - 1)];
      out__.write_free_lb(0, sigma_t0_culmeso);
      local_scalar_t__ sigma_k_culmeso = DUMMY_VAR__;
      current_statement__ = 10;
      sigma_k_culmeso = context__.vals_r("sigma_k_culmeso")[(1 - 1)];
      out__.write_free_lb(0, sigma_k_culmeso);
      local_scalar_t__ sigma_b_culmeso = DUMMY_VAR__;
      current_statement__ = 11;
      sigma_b_culmeso = context__.vals_r("sigma_b_culmeso")[(1 - 1)];
      out__.write_free_lb(0, sigma_b_culmeso);
      local_scalar_t__ sigma_scaledRI_cul = DUMMY_VAR__;
      current_statement__ = 12;
      sigma_scaledRI_cul = context__.vals_r("sigma_scaledRI_cul")[(1 - 1)];
      out__.write_free_lb(0, sigma_scaledRI_cul);
      local_scalar_t__ sigma_scaledRI_meso = DUMMY_VAR__;
      current_statement__ = 13;
      sigma_scaledRI_meso = context__.vals_r("sigma_scaledRI_meso")[(1 - 1)];
      out__.write_free_lb(0, sigma_scaledRI_meso);
      local_scalar_t__ sigma_scaledRI_crtp = DUMMY_VAR__;
      current_statement__ = 14;
      sigma_scaledRI_crtp = context__.vals_r("sigma_scaledRI_crtp")[(1 - 1)];
      out__.write_free_lb(0, sigma_scaledRI_crtp);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"t0_culmeso", "k_culmeso",
                "b_culmeso", "t0_crtp", "k_crtp", "b_crtp",
                "beta0_gdgt23ratio_crtp", "beta0_no3_crtp",
                "sigma_t0_culmeso", "sigma_k_culmeso", "sigma_b_culmeso",
                "sigma_scaledRI_cul", "sigma_scaledRI_meso",
                "sigma_scaledRI_crtp"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "t0_culmeso");
    param_names__.emplace_back(std::string() + "k_culmeso");
    param_names__.emplace_back(std::string() + "b_culmeso");
    param_names__.emplace_back(std::string() + "t0_crtp");
    param_names__.emplace_back(std::string() + "k_crtp");
    param_names__.emplace_back(std::string() + "b_crtp");
    param_names__.emplace_back(std::string() + "beta0_gdgt23ratio_crtp");
    param_names__.emplace_back(std::string() + "beta0_no3_crtp");
    param_names__.emplace_back(std::string() + "sigma_t0_culmeso");
    param_names__.emplace_back(std::string() + "sigma_k_culmeso");
    param_names__.emplace_back(std::string() + "sigma_b_culmeso");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_cul");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_meso");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_crtp");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "t0_culmeso");
    param_names__.emplace_back(std::string() + "k_culmeso");
    param_names__.emplace_back(std::string() + "b_culmeso");
    param_names__.emplace_back(std::string() + "t0_crtp");
    param_names__.emplace_back(std::string() + "k_crtp");
    param_names__.emplace_back(std::string() + "b_crtp");
    param_names__.emplace_back(std::string() + "beta0_gdgt23ratio_crtp");
    param_names__.emplace_back(std::string() + "beta0_no3_crtp");
    param_names__.emplace_back(std::string() + "sigma_t0_culmeso");
    param_names__.emplace_back(std::string() + "sigma_k_culmeso");
    param_names__.emplace_back(std::string() + "sigma_b_culmeso");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_cul");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_meso");
    param_names__.emplace_back(std::string() + "sigma_scaledRI_crtp");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"t0_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"t0_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta0_gdgt23ratio_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta0_no3_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_t0_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_k_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_b_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_cul\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_meso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"t0_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"t0_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta0_gdgt23ratio_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta0_no3_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_t0_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_k_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_b_culmeso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_cul\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_meso\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_scaledRI_crtp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1)
      + 1) + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1)
      + 1) + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = jnt_cul_meso_hier_crtp_multiv_archive_model_namespace::jnt_cul_meso_hier_crtp_multiv_archive_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return jnt_cul_meso_hier_crtp_multiv_archive_model_namespace::profiles__;
}
#endif