// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace joint_culture_meso_hierarchical_coretop_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 63> locations_array__ =
  {" (found before start of program)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 55, column 2 to column 29)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 56, column 2 to column 28)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 57, column 2 to column 22)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 60, column 2 to column 28)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 61, column 2 to column 27)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 62, column 2 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 65, column 2 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 66, column 2 to column 25)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 67, column 2 to column 19)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 70, column 2 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 71, column 2 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 72, column 2 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 77, column 2 to column 47)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 80, column 2 to column 65)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 81, column 2 to column 64)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 82, column 2 to column 64)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 83, column 2 to column 51)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 121, column 2 to column 39)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 122, column 2 to column 39)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 88, column 2 to column 35)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 88, column 28 to column 31)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 89, column 2 to column 26)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 92, column 2 to column 51)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 95, column 2 to column 30)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 96, column 2 to column 30)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 97, column 2 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 100, column 2 to column 29)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 101, column 2 to column 29)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 102, column 2 to column 29)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 105, column 2 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 105, column 28 to column 32)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 106, column 2 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 106, column 28 to column 32)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 107, column 2 to column 36)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 107, column 28 to column 32)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 110, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 110, column 2 to column 64)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 111, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 111, column 2 to column 64)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 112, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 112, column 2 to column 66)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 114, column 2 to column 37)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 114, column 29 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 115, column 2 to column 37)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 115, column 29 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 116, column 2 to column 37)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 116, column 29 to column 33)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 40, column 2 to column 18)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 41, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 41, column 2 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 42, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 42, column 2 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 44, column 2 to column 18)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 45, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 45, column 2 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 46, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 46, column 2 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 48, column 2 to column 18)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 49, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 49, column 2 to column 16)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 50, column 9 to column 11)",
  " (in '/home/ronnie-rattan/Documents/GitHub/culRI-Bayesian/culRIBayesian/stan_models/joint_culture_meso_hierarchical_coretop.stan', line 50, column 2 to column 16)"};
class joint_culture_meso_hierarchical_coretop_model final : public model_base_crtp<joint_culture_meso_hierarchical_coretop_model> {
 private:
  int N1;
  Eigen::Matrix<double,-1,1> x1_data__;
  Eigen::Matrix<double,-1,1> y1_data__;
  int N2;
  Eigen::Matrix<double,-1,1> x2_data__;
  Eigen::Matrix<double,-1,1> y2_data__;
  int N3;
  Eigen::Matrix<double,-1,1> x3_data__;
  Eigen::Matrix<double,-1,1> y3_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> x1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> x2{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y2{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> x3{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y3{nullptr, 0};
 public:
  ~joint_culture_meso_hierarchical_coretop_model() {}
  joint_culture_meso_hierarchical_coretop_model(stan::io::var_context&
                                                context__, unsigned int
                                                random_seed__ = 0,
                                                std::ostream*
                                                pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "joint_culture_meso_hierarchical_coretop_model_namespace::joint_culture_meso_hierarchical_coretop_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 48;
      context__.validate_dims("data initialization", "N1", "int",
        std::vector<size_t>{});
      N1 = std::numeric_limits<int>::min();
      current_statement__ = 48;
      N1 = context__.vals_i("N1")[(1 - 1)];
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "N1", N1, 1);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("x1", "N1", N1);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "x1", "double",
        std::vector<size_t>{static_cast<size_t>(N1)});
      x1_data__ = Eigen::Matrix<double,-1,1>::Constant(N1,
                    std::numeric_limits<double>::quiet_NaN());
      new (&x1) Eigen::Map<Eigen::Matrix<double,-1,1>>(x1_data__.data(), N1);
      {
        std::vector<local_scalar_t__> x1_flat__;
        current_statement__ = 50;
        x1_flat__ = context__.vals_r("x1");
        current_statement__ = 50;
        pos__ = 1;
        current_statement__ = 50;
        for (int sym1__ = 1; sym1__ <= N1; ++sym1__) {
          current_statement__ = 50;
          stan::model::assign(x1, x1_flat__[(pos__ - 1)],
            "assigning variable x1", stan::model::index_uni(sym1__));
          current_statement__ = 50;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 51;
      stan::math::validate_non_negative_index("y1", "N1", N1);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "y1", "double",
        std::vector<size_t>{static_cast<size_t>(N1)});
      y1_data__ = Eigen::Matrix<double,-1,1>::Constant(N1,
                    std::numeric_limits<double>::quiet_NaN());
      new (&y1) Eigen::Map<Eigen::Matrix<double,-1,1>>(y1_data__.data(), N1);
      {
        std::vector<local_scalar_t__> y1_flat__;
        current_statement__ = 52;
        y1_flat__ = context__.vals_r("y1");
        current_statement__ = 52;
        pos__ = 1;
        current_statement__ = 52;
        for (int sym1__ = 1; sym1__ <= N1; ++sym1__) {
          current_statement__ = 52;
          stan::model::assign(y1, y1_flat__[(pos__ - 1)],
            "assigning variable y1", stan::model::index_uni(sym1__));
          current_statement__ = 52;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 53;
      context__.validate_dims("data initialization", "N2", "int",
        std::vector<size_t>{});
      N2 = std::numeric_limits<int>::min();
      current_statement__ = 53;
      N2 = context__.vals_i("N2")[(1 - 1)];
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "N2", N2, 1);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("x2", "N2", N2);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "x2", "double",
        std::vector<size_t>{static_cast<size_t>(N2)});
      x2_data__ = Eigen::Matrix<double,-1,1>::Constant(N2,
                    std::numeric_limits<double>::quiet_NaN());
      new (&x2) Eigen::Map<Eigen::Matrix<double,-1,1>>(x2_data__.data(), N2);
      {
        std::vector<local_scalar_t__> x2_flat__;
        current_statement__ = 55;
        x2_flat__ = context__.vals_r("x2");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= N2; ++sym1__) {
          current_statement__ = 55;
          stan::model::assign(x2, x2_flat__[(pos__ - 1)],
            "assigning variable x2", stan::model::index_uni(sym1__));
          current_statement__ = 55;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 56;
      stan::math::validate_non_negative_index("y2", "N2", N2);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "y2", "double",
        std::vector<size_t>{static_cast<size_t>(N2)});
      y2_data__ = Eigen::Matrix<double,-1,1>::Constant(N2,
                    std::numeric_limits<double>::quiet_NaN());
      new (&y2) Eigen::Map<Eigen::Matrix<double,-1,1>>(y2_data__.data(), N2);
      {
        std::vector<local_scalar_t__> y2_flat__;
        current_statement__ = 57;
        y2_flat__ = context__.vals_r("y2");
        current_statement__ = 57;
        pos__ = 1;
        current_statement__ = 57;
        for (int sym1__ = 1; sym1__ <= N2; ++sym1__) {
          current_statement__ = 57;
          stan::model::assign(y2, y2_flat__[(pos__ - 1)],
            "assigning variable y2", stan::model::index_uni(sym1__));
          current_statement__ = 57;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 58;
      context__.validate_dims("data initialization", "N3", "int",
        std::vector<size_t>{});
      N3 = std::numeric_limits<int>::min();
      current_statement__ = 58;
      N3 = context__.vals_i("N3")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "N3", N3, 1);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("x3", "N3", N3);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "x3", "double",
        std::vector<size_t>{static_cast<size_t>(N3)});
      x3_data__ = Eigen::Matrix<double,-1,1>::Constant(N3,
                    std::numeric_limits<double>::quiet_NaN());
      new (&x3) Eigen::Map<Eigen::Matrix<double,-1,1>>(x3_data__.data(), N3);
      {
        std::vector<local_scalar_t__> x3_flat__;
        current_statement__ = 60;
        x3_flat__ = context__.vals_r("x3");
        current_statement__ = 60;
        pos__ = 1;
        current_statement__ = 60;
        for (int sym1__ = 1; sym1__ <= N3; ++sym1__) {
          current_statement__ = 60;
          stan::model::assign(x3, x3_flat__[(pos__ - 1)],
            "assigning variable x3", stan::model::index_uni(sym1__));
          current_statement__ = 60;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 61;
      stan::math::validate_non_negative_index("y3", "N3", N3);
      current_statement__ = 62;
      context__.validate_dims("data initialization", "y3", "double",
        std::vector<size_t>{static_cast<size_t>(N3)});
      y3_data__ = Eigen::Matrix<double,-1,1>::Constant(N3,
                    std::numeric_limits<double>::quiet_NaN());
      new (&y3) Eigen::Map<Eigen::Matrix<double,-1,1>>(y3_data__.data(), N3);
      {
        std::vector<local_scalar_t__> y3_flat__;
        current_statement__ = 62;
        y3_flat__ = context__.vals_r("y3");
        current_statement__ = 62;
        pos__ = 1;
        current_statement__ = 62;
        for (int sym1__ = 1; sym1__ <= N3; ++sym1__) {
          current_statement__ = 62;
          stan::model::assign(y3, y3_flat__[(pos__ - 1)],
            "assigning variable y3", stan::model::index_uni(sym1__));
          current_statement__ = 62;
          pos__ = (pos__ + 1);
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "joint_culture_meso_hierarchical_coretop_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = "};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "joint_culture_meso_hierarchical_coretop_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ x0 = DUMMY_VAR__;
      current_statement__ = 1;
      x0 = in__.template read_constrain_lb<local_scalar_t__,
             jacobian__>(-1.8, lp__);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 2;
      k = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(1e-6,
            lp__);
      local_scalar_t__ logit_b = DUMMY_VAR__;
      current_statement__ = 3;
      logit_b = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma_x0 = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_x0 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(1e-6, lp__);
      local_scalar_t__ sigma_k = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_k = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(1e-6, lp__);
      local_scalar_t__ sigma_logit_b = DUMMY_VAR__;
      current_statement__ = 6;
      sigma_logit_b = in__.template read_constrain_lb<local_scalar_t__,
                        jacobian__>(1e-6, lp__);
      local_scalar_t__ z_x0_3 = DUMMY_VAR__;
      current_statement__ = 7;
      z_x0_3 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(-1.8, lp__);
      local_scalar_t__ z_k_3 = DUMMY_VAR__;
      current_statement__ = 8;
      z_k_3 = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(1e-6, lp__);
      local_scalar_t__ z_logit_b_3 = DUMMY_VAR__;
      current_statement__ = 9;
      z_logit_b_3 = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma1 = DUMMY_VAR__;
      current_statement__ = 10;
      sigma1 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(1e-6, lp__);
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      current_statement__ = 11;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(1e-6, lp__);
      local_scalar_t__ sigma3 = DUMMY_VAR__;
      current_statement__ = 12;
      sigma3 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(1e-6, lp__);
      local_scalar_t__ b = DUMMY_VAR__;
      current_statement__ = 13;
      b = stan::math::inv_logit(logit_b);
      local_scalar_t__ x0_3 = DUMMY_VAR__;
      current_statement__ = 14;
      x0_3 = (x0 + (sigma_x0 * z_x0_3));
      local_scalar_t__ k_3 = DUMMY_VAR__;
      current_statement__ = 15;
      k_3 = (k + (sigma_k * z_k_3));
      local_scalar_t__ logit_b_3 = DUMMY_VAR__;
      current_statement__ = 16;
      logit_b_3 = (logit_b + (sigma_logit_b * z_logit_b_3));
      local_scalar_t__ b_3 = DUMMY_VAR__;
      current_statement__ = 17;
      b_3 = stan::math::inv_logit(logit_b_3);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "b", b, 0);
      current_statement__ = 13;
      stan::math::check_less_or_equal(function__, "b", b, 1);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "x0_3", x0_3, -1.8);
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "k_3", k_3, 1e-6);
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "b_3", b_3, 0);
      current_statement__ = 17;
      stan::math::check_less_or_equal(function__, "b_3", b_3, 1);
      {
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(x0, 30, 10));
        current_statement__ = 21;
        if (stan::math::logical_lt(x0, -1.8)) {
          current_statement__ = 21;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 21;
          lp_accum__.add(-stan::math::normal_lccdf(-1.8, 30, 10));
        }
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(k, 0, 0.25));
        current_statement__ = 23;
        lp_accum__.add((stan::math::beta_lpdf<false>(b, 2, 5) +
          stan::math::log((b * (1 - b)))));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_x0, 0, 1));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_k, 0, 1));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_logit_b, 0,
                         0.2));
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(z_x0_3, 0, 1));
        current_statement__ = 28;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(z_k_3, 0, 1));
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(z_logit_b_3, 0, 1));
        current_statement__ = 30;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma1, 0, 0.1));
        current_statement__ = 31;
        if (stan::math::logical_lt(sigma1, 1e-6)) {
          current_statement__ = 31;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 31;
          lp_accum__.add(-stan::math::normal_lccdf(1e-6, 0, 0.1));
        }
        current_statement__ = 32;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma2, 0, 0.1));
        current_statement__ = 33;
        if (stan::math::logical_lt(sigma2, 1e-6)) {
          current_statement__ = 33;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 33;
          lp_accum__.add(-stan::math::normal_lccdf(1e-6, 0, 0.1));
        }
        current_statement__ = 34;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma3, 0, 0.1));
        current_statement__ = 35;
        if (stan::math::logical_lt(sigma3, 1e-6)) {
          current_statement__ = 35;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 35;
          lp_accum__.add(-stan::math::normal_lccdf(1e-6, 0, 0.1));
        }
        current_statement__ = 36;
        stan::math::validate_non_negative_index("mu1", "N1", N1);
        Eigen::Matrix<local_scalar_t__,-1,1> mu1 =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N1, DUMMY_VAR__);
        current_statement__ = 37;
        stan::model::assign(mu1,
          stan::math::add(
            stan::math::multiply((1 - b),
              stan::math::inv_logit(
                stan::math::multiply(k, stan::math::subtract(x1, x0)))), b),
          "assigning variable mu1");
        current_statement__ = 38;
        stan::math::validate_non_negative_index("mu2", "N2", N2);
        Eigen::Matrix<local_scalar_t__,-1,1> mu2 =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N2, DUMMY_VAR__);
        current_statement__ = 39;
        stan::model::assign(mu2,
          stan::math::add(
            stan::math::multiply((1 - b),
              stan::math::inv_logit(
                stan::math::multiply(k, stan::math::subtract(x2, x0)))), b),
          "assigning variable mu2");
        current_statement__ = 40;
        stan::math::validate_non_negative_index("mu3", "N3", N3);
        Eigen::Matrix<local_scalar_t__,-1,1> mu3 =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N3, DUMMY_VAR__);
        current_statement__ = 41;
        stan::model::assign(mu3,
          stan::math::add(
            stan::math::multiply((1 - b_3),
              stan::math::inv_logit(
                stan::math::multiply(k_3, stan::math::subtract(x3, x0_3)))),
            b_3), "assigning variable mu3");
        current_statement__ = 42;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y1, mu1, sigma1));
        current_statement__ = 43;
        if (stan::math::logical_lt(stan::math::min(y1), 1e-6)) {
          current_statement__ = 43;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 43;
          lp_accum__.add(-stan::math::normal_lccdf(1e-6, mu1, sigma1));
        }
        current_statement__ = 44;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y2, mu2, sigma2));
        current_statement__ = 45;
        if (stan::math::logical_lt(stan::math::min(y2), 1e-6)) {
          current_statement__ = 45;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 45;
          lp_accum__.add(-stan::math::normal_lccdf(1e-6, mu2, sigma2));
        }
        current_statement__ = 46;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y3, mu3, sigma3));
        current_statement__ = 47;
        if (stan::math::logical_lt(stan::math::min(y3), 1e-6)) {
          current_statement__ = 47;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 47;
          lp_accum__.add(-stan::math::normal_lccdf(1e-6, mu3, sigma3));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "joint_culture_meso_hierarchical_coretop_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double x0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      x0 = in__.template read_constrain_lb<local_scalar_t__,
             jacobian__>(-1.8, lp__);
      double k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      k = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(1e-6,
            lp__);
      double logit_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      logit_b = in__.template read<local_scalar_t__>();
      double sigma_x0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma_x0 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(1e-6, lp__);
      double sigma_k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma_k = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(1e-6, lp__);
      double sigma_logit_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      sigma_logit_b = in__.template read_constrain_lb<local_scalar_t__,
                        jacobian__>(1e-6, lp__);
      double z_x0_3 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      z_x0_3 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(-1.8, lp__);
      double z_k_3 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      z_k_3 = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(1e-6, lp__);
      double z_logit_b_3 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      z_logit_b_3 = in__.template read<local_scalar_t__>();
      double sigma1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 10;
      sigma1 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(1e-6, lp__);
      double sigma2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(1e-6, lp__);
      double sigma3 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      sigma3 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(1e-6, lp__);
      double b = std::numeric_limits<double>::quiet_NaN();
      double x0_3 = std::numeric_limits<double>::quiet_NaN();
      double k_3 = std::numeric_limits<double>::quiet_NaN();
      double logit_b_3 = std::numeric_limits<double>::quiet_NaN();
      double b_3 = std::numeric_limits<double>::quiet_NaN();
      out__.write(x0);
      out__.write(k);
      out__.write(logit_b);
      out__.write(sigma_x0);
      out__.write(sigma_k);
      out__.write(sigma_logit_b);
      out__.write(z_x0_3);
      out__.write(z_k_3);
      out__.write(z_logit_b_3);
      out__.write(sigma1);
      out__.write(sigma2);
      out__.write(sigma3);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 13;
      b = stan::math::inv_logit(logit_b);
      current_statement__ = 14;
      x0_3 = (x0 + (sigma_x0 * z_x0_3));
      current_statement__ = 15;
      k_3 = (k + (sigma_k * z_k_3));
      current_statement__ = 16;
      logit_b_3 = (logit_b + (sigma_logit_b * z_logit_b_3));
      current_statement__ = 17;
      b_3 = stan::math::inv_logit(logit_b_3);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "b", b, 0);
      current_statement__ = 13;
      stan::math::check_less_or_equal(function__, "b", b, 1);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "x0_3", x0_3, -1.8);
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "k_3", k_3, 1e-6);
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "b_3", b_3, 0);
      current_statement__ = 17;
      stan::math::check_less_or_equal(function__, "b_3", b_3, 1);
      if (emit_transformed_parameters__) {
        out__.write(b);
        out__.write(x0_3);
        out__.write(k_3);
        out__.write(logit_b_3);
        out__.write(b_3);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double sigma2_sigma1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 18;
      sigma2_sigma1 = (sigma2 / sigma1);
      double sigma3_sigma1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 19;
      sigma3_sigma1 = (sigma3 / sigma1);
      out__.write(sigma2_sigma1);
      out__.write(sigma3_sigma1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ x0 = DUMMY_VAR__;
      current_statement__ = 1;
      x0 = in__.read<local_scalar_t__>();
      out__.write_free_lb(-1.8, x0);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 2;
      k = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, k);
      local_scalar_t__ logit_b = DUMMY_VAR__;
      current_statement__ = 3;
      logit_b = in__.read<local_scalar_t__>();
      out__.write(logit_b);
      local_scalar_t__ sigma_x0 = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_x0 = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, sigma_x0);
      local_scalar_t__ sigma_k = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_k = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, sigma_k);
      local_scalar_t__ sigma_logit_b = DUMMY_VAR__;
      current_statement__ = 6;
      sigma_logit_b = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, sigma_logit_b);
      local_scalar_t__ z_x0_3 = DUMMY_VAR__;
      current_statement__ = 7;
      z_x0_3 = in__.read<local_scalar_t__>();
      out__.write_free_lb(-1.8, z_x0_3);
      local_scalar_t__ z_k_3 = DUMMY_VAR__;
      current_statement__ = 8;
      z_k_3 = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, z_k_3);
      local_scalar_t__ z_logit_b_3 = DUMMY_VAR__;
      current_statement__ = 9;
      z_logit_b_3 = in__.read<local_scalar_t__>();
      out__.write(z_logit_b_3);
      local_scalar_t__ sigma1 = DUMMY_VAR__;
      current_statement__ = 10;
      sigma1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, sigma1);
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      current_statement__ = 11;
      sigma2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, sigma2);
      local_scalar_t__ sigma3 = DUMMY_VAR__;
      current_statement__ = 12;
      sigma3 = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, sigma3);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "x0", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "k", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "logit_b",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma_x0",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sigma_k",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "sigma_logit_b",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "z_x0_3", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "z_k_3", "double",
        std::vector<size_t>{});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "z_logit_b_3",
        "double", std::vector<size_t>{});
      current_statement__ = 10;
      context__.validate_dims("parameter initialization", "sigma1", "double",
        std::vector<size_t>{});
      current_statement__ = 11;
      context__.validate_dims("parameter initialization", "sigma2", "double",
        std::vector<size_t>{});
      current_statement__ = 12;
      context__.validate_dims("parameter initialization", "sigma3", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ x0 = DUMMY_VAR__;
      current_statement__ = 1;
      x0 = context__.vals_r("x0")[(1 - 1)];
      out__.write_free_lb(-1.8, x0);
      local_scalar_t__ k = DUMMY_VAR__;
      current_statement__ = 2;
      k = context__.vals_r("k")[(1 - 1)];
      out__.write_free_lb(1e-6, k);
      local_scalar_t__ logit_b = DUMMY_VAR__;
      current_statement__ = 3;
      logit_b = context__.vals_r("logit_b")[(1 - 1)];
      out__.write(logit_b);
      local_scalar_t__ sigma_x0 = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_x0 = context__.vals_r("sigma_x0")[(1 - 1)];
      out__.write_free_lb(1e-6, sigma_x0);
      local_scalar_t__ sigma_k = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_k = context__.vals_r("sigma_k")[(1 - 1)];
      out__.write_free_lb(1e-6, sigma_k);
      local_scalar_t__ sigma_logit_b = DUMMY_VAR__;
      current_statement__ = 6;
      sigma_logit_b = context__.vals_r("sigma_logit_b")[(1 - 1)];
      out__.write_free_lb(1e-6, sigma_logit_b);
      local_scalar_t__ z_x0_3 = DUMMY_VAR__;
      current_statement__ = 7;
      z_x0_3 = context__.vals_r("z_x0_3")[(1 - 1)];
      out__.write_free_lb(-1.8, z_x0_3);
      local_scalar_t__ z_k_3 = DUMMY_VAR__;
      current_statement__ = 8;
      z_k_3 = context__.vals_r("z_k_3")[(1 - 1)];
      out__.write_free_lb(1e-6, z_k_3);
      local_scalar_t__ z_logit_b_3 = DUMMY_VAR__;
      current_statement__ = 9;
      z_logit_b_3 = context__.vals_r("z_logit_b_3")[(1 - 1)];
      out__.write(z_logit_b_3);
      local_scalar_t__ sigma1 = DUMMY_VAR__;
      current_statement__ = 10;
      sigma1 = context__.vals_r("sigma1")[(1 - 1)];
      out__.write_free_lb(1e-6, sigma1);
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      current_statement__ = 11;
      sigma2 = context__.vals_r("sigma2")[(1 - 1)];
      out__.write_free_lb(1e-6, sigma2);
      local_scalar_t__ sigma3 = DUMMY_VAR__;
      current_statement__ = 12;
      sigma3 = context__.vals_r("sigma3")[(1 - 1)];
      out__.write_free_lb(1e-6, sigma3);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"x0", "k", "logit_b", "sigma_x0",
                "sigma_k", "sigma_logit_b", "z_x0_3", "z_k_3", "z_logit_b_3",
                "sigma1", "sigma2", "sigma3"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"b", "x0_3", "k_3", "logit_b_3", "b_3"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"sigma2_sigma1", "sigma3_sigma1"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "x0");
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "logit_b");
    param_names__.emplace_back(std::string() + "sigma_x0");
    param_names__.emplace_back(std::string() + "sigma_k");
    param_names__.emplace_back(std::string() + "sigma_logit_b");
    param_names__.emplace_back(std::string() + "z_x0_3");
    param_names__.emplace_back(std::string() + "z_k_3");
    param_names__.emplace_back(std::string() + "z_logit_b_3");
    param_names__.emplace_back(std::string() + "sigma1");
    param_names__.emplace_back(std::string() + "sigma2");
    param_names__.emplace_back(std::string() + "sigma3");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "b");
      param_names__.emplace_back(std::string() + "x0_3");
      param_names__.emplace_back(std::string() + "k_3");
      param_names__.emplace_back(std::string() + "logit_b_3");
      param_names__.emplace_back(std::string() + "b_3");
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "sigma2_sigma1");
      param_names__.emplace_back(std::string() + "sigma3_sigma1");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "x0");
    param_names__.emplace_back(std::string() + "k");
    param_names__.emplace_back(std::string() + "logit_b");
    param_names__.emplace_back(std::string() + "sigma_x0");
    param_names__.emplace_back(std::string() + "sigma_k");
    param_names__.emplace_back(std::string() + "sigma_logit_b");
    param_names__.emplace_back(std::string() + "z_x0_3");
    param_names__.emplace_back(std::string() + "z_k_3");
    param_names__.emplace_back(std::string() + "z_logit_b_3");
    param_names__.emplace_back(std::string() + "sigma1");
    param_names__.emplace_back(std::string() + "sigma2");
    param_names__.emplace_back(std::string() + "sigma3");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "b");
      param_names__.emplace_back(std::string() + "x0_3");
      param_names__.emplace_back(std::string() + "k_3");
      param_names__.emplace_back(std::string() + "logit_b_3");
      param_names__.emplace_back(std::string() + "b_3");
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "sigma2_sigma1");
      param_names__.emplace_back(std::string() + "sigma3_sigma1");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"x0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"logit_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_x0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_logit_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_x0_3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_k_3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_logit_b_3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"x0_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"k_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"logit_b_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"b_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma2_sigma1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma3_sigma1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"x0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"logit_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_x0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_logit_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_x0_3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_k_3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_logit_b_3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"x0_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"k_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"logit_b_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"b_3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma2_sigma1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma3_sigma1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) +
      1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((((1 + 1)
      + 1) + 1) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) +
      1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((((1 + 1)
      + 1) + 1) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = joint_culture_meso_hierarchical_coretop_model_namespace::joint_culture_meso_hierarchical_coretop_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return joint_culture_meso_hierarchical_coretop_model_namespace::profiles__;
}
#endif