site_name: TEXAS

theme:
  name: material

plugins:
  - search
  - mkdocstrings
  
nav:
  - Quickstart: index.md
  - API Reference:
      - “TEXAS”: api.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
